version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bankdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: bankingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ← added this

  app:
    build: .
    container_name: banking-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: psql

volumes:
  postgres_data:  # ← declared volume here